# Experiments with loading 01
> Contains some experiments with implemented functions

In [ ]:
from fastai.tabular.all import *
import json
import torch
from torch.autograd import Variable

from transfertab.utils import *
from transfertab.core import *

In [ ]:
df2 = pd.read_csv('../data/toy_dataset.csv')
splits2 = RandomSplitter(valid_pct=0.2)(range_of(df2))
to2 = TabularPandas(df2, procs=[Categorify, FillMissing,Normalize],
                   cat_names = ['City','sex'],
                   cont_names = ['Number', 'Income', 'Age'],
                   y_names='Illness',
                   splits=splits2)
dls2 = to2.dataloaders(bs=64)
learn2 = tabular_learner(dls2, metrics=accuracy)

In [ ]:
learn2.fit(1)

In [ ]:
row, clas, probs = learn2.predict(df2.iloc[-1])
row, clas, probs

(   City  sex    Number    Income       Age  Illness
 0   1.0  1.0  1.730331 -0.159314 -0.684358      0.0,
 tensor(0),
 tensor([0.9196, 0.0804]))

In [ ]:
tab_obj = TabTransfer(learn2)

In [ ]:
# tab_obj.read_json("toy_dataset.json")

In [ ]:
# tab_obj.transfer(["sex"], verbose = True)

tensor([[ 0.0078, -0.0057,  0.0079],
        [ 0.0084, -0.0047,  0.0006],
        [-0.0068, -0.0055,  0.0075]])
mean is tensor([ 0.0031, -0.0053,  0.0053]) for tensor([[ 0.0078, -0.0057,  0.0079],
        [ 0.0084, -0.0047,  0.0006],
        [-0.0068, -0.0055,  0.0075]])
0, <class 'int'>
Transferring weights for class #na#, cat sex using mean
old weight for class is tensor([ 0.0031, -0.0053,  0.0053], grad_fn=<SliceBackward>)
new weight for class is tensor([ 0.0031, -0.0053,  0.0053], grad_fn=<SliceBackward>)
1, <class 'int'>
Transferring weights for class Female, cat sex from previous weights
old weight for class is tensor([ 0.0078, -0.0057,  0.0079], grad_fn=<SliceBackward>)
new weight for class is tensor([ 0.0078, -0.0057,  0.0079], grad_fn=<SliceBackward>)
2, <class 'int'>
Transferring weights for class Male, cat sex from previous weights
old weight for class is tensor([ 0.0084, -0.0047,  0.0006], grad_fn=<SliceBackward>)
new weight for class is tensor([ 0.0084, -0.0047,  0.0006], 

In [ ]:
# tab_obj.save_pickle('test_pickle')

In [ ]:
# new_model = tab_obj.load_pickle('test_pickle')

In [ ]:
# row_new_model, clas_new_model, probs_new_model = new_model.predict(df2.iloc[-1])

In [ ]:
# row_new_model.show()

In [ ]:
# clas_new_model, probs_new_model

(tensor(0), tensor([0.9316, 0.0684]))

##### =============================== #####

In [ ]:
# row, clas, probs = learn2.predict(df2.iloc[-1])

In [ ]:
# row.show()

In [ ]:
# clas, probs

(tensor(0), tensor([0.9018, 0.0982]))

In [ ]:
# learner_row, learner_clas, learner_probs = new_model.predict(df2.iloc[-1])

In [ ]:
# learner_row.show()

In [ ]:
# learner_probs

tensor([0.9316, 0.0684])